### ISSUE TITLE
run time error when notarizing munki 5.5

### ISSUE THREAD

**Issue by dev-yeet** [lifeunexpected/Scripts#5] opened 2021-06-11 20:23 UTC
not really an issue with your script but more so of the current version of python (I believe it got bumped to 3.9.5)

https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma125/v4/08/9e/b4/089eb446-2735-122e-c034-de359bb35368/developer_log.json?accessKey=1623636886_1426937396114077386_XsGzRwj7zzpg%2ByPjnXcDutdsW4955wL9erMRE9awwFwZzVuSZztIQKx86SYJ%2BfgM4cchm9zD5ObtA5dMVaWcVvmgXr4aSDB3FNGYt0h4LgMh40gXtr4u64Fc%2FDcZrY3GxzDNryWhQOW6Qk8K09XucoAxTWsF9CvQ4ctwNxqa4Sc%3D

**Comment by lifeunexpected** [comment] 2021-06-30 10:46
Hey
Yes i seem to experience the same problem and trying to look into how to solve it but not having any luck yet.
https://groups.google.com/g/munki-dev/c/gsg9QTesNNI

Im also having some issue with xattr not being installed correct and this causes problems for me.

So im looking into it but maybe it gets fixed in the next version of python

**Comment by lifeunexpected** [comment] 2021-08-16 12:44
Hey after a lot of searching i found the solution for what might cause your problem.

Greag Neagle posted this issue and in his original post he mentioned what OS and xcode version he was trying to build under and what OS and xcode version caused problems.
https://github.com/ronaldoussoren/pyobjc/issues/370

Worked for him: Xcode 12.3 and 12.4 
Failed with:  Xcode 12.5 and 12.5.1
OS: macOS 11.4 worked, but he also mentions that the issue was observed with macOS 11.2.1 and above 

What i then did was download macOS 11.4 using the installinstallmacos.py from https://github.com/munki/macadmin-scripts and download xcode 12.4 from https://developer.apple.com/download/more/ and just searched for the xcode version i wanted.

After re-installing one of my extra macs with the macOS 11.4 from a usb drive and downloaded and installed xcode version 12.4 that Greag mentioned and it worked.

Tips: You will probably get a info box like the image below when you try too boot from usb stick after the OS is booted so just follow the information in the picture to solve it.

https://i.stack.imgur.com/IxzAt.jpg

The machine i used now where things worked is the following:
Machine: Macbook Pro 2018
CPU: Intel
OS: macOS 11.4  maybe 11.5 will work but i havent tried.
Xcode: 12.4 (12.3 might work) 12.5 and 12.5.1 DONT work
Munki v5.4.0 - Working no xattr or other error messages - Notarization approved - Package valid for use
Munki v5.5.0 - Notaraziation not approved 
"path": "munkitools-5.5.0.4362.pkg/munkitools_python.pkg Contents/Payload/usr/local/munki/Python.framework/Versions/3.9/bin/python3.9-intel64",
"message": "The executable does not have the hardened runtime enabled.",
Se post below for more details

Im going to test with Apple M1 after this but it didnt work originally on Intel either and my boss only gave me one Apple M1 mac :P And that is now my primary machine so kinda didnt want re-install that just for fun.

Update: I tested again with the Apple M1 cpu and got the following results.

Machine: Macbook Pro 2020
CPU: Apple M1
OS: macOS 11.4  maybe 11.5 will work but i havent tried. (clean install)
Xcode: (12.3 might work) 12.4 , 12.5 and 12.5.1 DONT work
Result: 
Munki v5.4.0 - Not working xattr error messages - Notaraziation Approved but package is semi-defective so you shouldnt use it
Munki v5.5.0 - Not working xattr error messages - Notarization not approved

**Comment by lifeunexpected** [comment] 2021-08-16 12:46
munki v5.4.0 got notarized and approved not v5.5.0 so still need to look for the issue

**Comment by lifeunexpected** [comment] 2021-08-16 14:24
The problem with munki v5.5.0 is most likely cause by this file not having hardened runtime enabled as you can see below.

Munki v5.4.0 uses python 3.9.4 and this work
Munki v5.5.0 uses python 3.9.5 that dont work and neither do python 3.9.6 they both give the same error when trying to notarize.

"path": "munkitools-5.5.0.4362.pkg/munkitools_python.pkg Contents/Payload/usr/local/munki/Python.framework/Versions/3.9/bin/python3.9-intel64",
      "message": "The executable does not have the hardened runtime enabled.",
      
 Probably have to look into why this file dont have hardened runtime enabled.
 
 Update: The problem regarding xattr seems to be an Apple M1 cpu issue caused by pyobjc but the developer is working on an update/fix for that problem.
 
Regarding notarization on munki v5.5.0 the problem is seems to be caused by "python3.9-intel64" this  "The executable does not have the hardened runtime enabled." This issue is seen in python v3.9.5 and 3.9.6 but not in 3.9.4 since 3.9.4 dont have the "python3.9.4-Intel64" file. This problem will be reported as an issue on pythons github.

its now been reported https://bugs.python.org/issue44933

**Comment by lifeunexpected** [comment] 2021-08-19 11:34
this is now solved with the latest update to Munki.Notarize.zsh 

you need to codesign python3.9-intel64 of course but the original code only codesigned python3.x

codesign --force --options runtime --entitlements $MUNKIROOT/entitlements.plist --deep --verbose -s "$DevApp" $MUNKIROOT/Python.framework/Versions/$PYTHON_FRAMEWORK_VERSION/bin/"python$PYTHON_FRAMEWORK_VERSION-intel64"

**Closed as completed by lifeunexpected** 2021-08-19 11:34 UTC

**Comment by lifeunexpected** [comment] 2021-08-19 11:46
You will still get xattr and/or pyobjc errors on Apple M1 cpus untill an update to xattr is released.
 This update is to add support for notarization not fixing xattr and pyobjc errors that is something the developer behind pyobjc and xattr needs to fix.
 
 Most likely an update to pyobjc will fix xattr but maybe xattr also needs to update something after the new version of pyobjc gets released. Im not sure because im not the developer being those things so ask them for help if those things fail :)
 
 Update: Building Munki v5.5.0 on Apple M1 cpu does work and it gets notarized and approved but, you shoudlnt deploy it since xattr/pyobjc causes you to get a semi-defected munki installation of the apps.

**Comment by dev-yeet** [comment] 2021-08-19 11:53
hey thanks for the update and investigating the issue. I'll have to test when I get a chance, hopefully we get a munki update soon b/c right now we just deployed the non notarized version.

**Comment by lifeunexpected** [comment] 2021-08-19 11:55
If you do have an Intel mac you can get v5.5.0 notarized so you can deploy that for now.

If you are still getting xattr or pyobjc errors just re-install a machine if you can with the following
Install: macOS 11.4 and xcode 12.4
